#!/usr/bin/python

# Authors:
#   Petr Viktorin <pviktori@redhat.com>
#   Jason Gerard DeRose <jderose@redhat.com>
#
# Copyright (C) 2008-2013  Red Hat
# see file 'COPYING' for use and warranty information
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Nose wrapper for running an installed (not in-tree) IPA test suite

Any command-line arguments are passed directly to Nose.
Note that any relative paths given will be based on the ipatests module's path
"""

import sys
import os
from os import path

import nose

import ipatests
from ipatests.beakerlib_plugin import BeakerLibPlugin
from ipatests.order_plugin import OrderTests

cmd = [
    sys.argv[0],
    '-v',
    '--with-doctest',
    '--doctest-tests',
    '--with-ordered-tests',
    '--exclude=plugins',
    '--where', os.path.dirname(ipatests.__file__),
]
cmd += sys.argv[1:]


# This must be set so ipalib.api gets initialized property for tests:
os.environ['IPA_UNIT_TEST_MODE'] = 'cli_test'

nose.main(argv=cmd, addplugins=[BeakerLibPlugin(), OrderTests()])
