# Copyright (C) 2025  FreeIPA Contributors see COPYING for license

"""KRA (Key Recovery Authority) helper for IPAThinCAInstance."""

from __future__ import absolute_import

import datetime
import logging
import shutil
from pathlib import Path

from cryptography import x509
from cryptography.x509.oid import NameOID
from cryptography.hazmat.primitives import serialization

from ipalib import errors
from ipaplatform.paths import paths
from ipapython.dn import DN

from ipathinca.kra import KRA
from ipathinca.nss_utils import NSSDatabase
from ipathinca.storage_factory import get_storage_backend
from ipathinca.storage_kra import KRAStorageBackend
from ipathinca.x509_utils import get_audit_key_usage_extension

from .certs import get_cert_params_from_config, convert_signing_algorithm

logger = logging.getLogger(__name__)


class KRAInstall:
    """Helper providing KRA subsystem methods."""

    def __init__(
        self,
        ldap,
        nssdb,
        ca_cert_path,
        realm,
        basedn,
        fqdn,
        pki_config,
        ldap_mod_fn,
    ):
        self.ldap = ldap
        self._nssdb = nssdb
        self.ca_cert_path = ca_cert_path
        self.realm = realm
        self.basedn = basedn
        self.fqdn = fqdn
        self.pki_config = pki_config
        self._ldap_mod = ldap_mod_fn

    @property
    def nssdb_dir(self):
        return self._nssdb.nssdb_dir

    @property
    def nssdb_password(self):
        return self._nssdb.nssdb_password

    def enable_kra(self):
        """Enable KRA functionality in ipathinca.

        This initializes the KRA (Key Recovery Authority) subsystem,
        generating transport and storage keys. Similar to how Dogtag
        handles KRA as a subsystem within pki-tomcat, ipathinca handles
        KRA as functionality within the ipathinca service.
        """
        logger.info("Enabling KRA in ipathinca")

        # Load NSSDB paths and password if not already set
        # (needed when enable_kra is called separately from create_instance)
        self._nssdb.load_nssdb_password()

        # Create KRA directory
        kra_dir = Path(paths.IPATHINCA_DIR) / "kra"
        kra_dir.mkdir(parents=True, exist_ok=True, mode=0o700)

        try:
            shutil.chown(kra_dir, user="ipaca", group="ipaca")
        except Exception as e:
            logger.warning(f"Could not set ownership on {kra_dir}: {e}")

        # Get storage backend for LDAP access and HSM support
        storage_backend = get_storage_backend(ca_id="kra")

        # Initialize KRA with storage backend (enables HSM support)
        kra = KRA(storage_backend=storage_backend, kra_id="kra")

        # Load CA certificate from file
        with open(self.ca_cert_path, "rb") as f:
            ca_cert = x509.load_pem_x509_certificate(f.read())

        # Extract CA private key from NSSDB (use the initialized helper)
        ca_nickname = "caSigningCert cert-pki-ca"
        logger.debug(f"Extracting CA private key from NSSDB: {ca_nickname}")
        nssdb = NSSDatabase(
            nssdb_dir=self._nssdb.nssdb_dir,
            password_file=self._nssdb.nssdb_password_file,
        )
        ca_key = nssdb.extract_private_key(ca_nickname)

        # Initialize KRA LDAP schema (creates o=kra,o=ipaca containers)
        kra_storage = KRAStorageBackend()
        kra_storage.init_schema()

        # Initialize KRA (generates/loads transport and storage keys)
        # KRA keys are generated directly in NSSDB (Dogtag-compatible)
        # No PEM file import needed - keys are already in NSSDB
        kra.initialize(ca_key, ca_cert, storage_backend)

        logger.debug(
            "KRA transport and storage certificates already in NSSDB "
            "(generated by kra.initialize)"
        )

        # Generate and import KRA audit signing certificate
        self._generate_kra_audit_cert(ca_key, ca_cert)

        # Create vault container structure in LDAP (same as Dogtag KRA)
        # This creates cn=kra,{basedn} and cn=vaults,cn=kra,{basedn}
        self._add_vault_container()

        # Register KRA service in LDAP (required for kra_is_enabled checks)
        self._register_kra_service()

        logger.info("KRA enabled successfully in ipathinca")

    def _generate_kra_audit_cert(self, ca_key, ca_cert):
        """Generate KRA audit signing certificate in NSSDB (Dogtag-compatible).

        Dogtag KRA has a separate audit signing certificate distinct from the
        CA audit signing certificate. This generates the key in NSSDB and
        imports the certificate.

        Args:
            ca_key: CA private key for signing
            ca_cert: CA certificate (issuer)
        """
        logger.debug(
            "Generating KRA audit signing certificate "
            "(Dogtag-compatible NSSDB storage)"
        )

        # Certificate nickname in NSSDB
        kra_audit_nickname = "auditSigningCert cert-pki-kra"

        # Initialize NSSDB access
        nssdb = NSSDatabase(
            nssdb_dir=self.nssdb_dir,
            nssdb_password=self.nssdb_password,
        )

        # Check if already exists in NSSDB
        if nssdb.cert_exists(kra_audit_nickname):
            logger.debug("KRA audit certificate already exists in NSSDB")
            return

        # Get certificate parameters from config
        key_size, signing_alg = get_cert_params_from_config(
            self.pki_config, "audit_signing"
        )
        hash_alg = convert_signing_algorithm(signing_alg)

        logger.debug(
            f"Generating KRA audit certificate (key_size={key_size}, "
            f"signing_alg={signing_alg})"
        )

        # Generate RSA key pair in memory (will be imported to NSSDB with cert)
        private_key = nssdb.generate_key_pair(
            kra_audit_nickname, key_size=key_size
        )

        # Create certificate subject
        subject = x509.Name(
            [
                x509.NameAttribute(NameOID.ORGANIZATION_NAME, self.realm),
                x509.NameAttribute(
                    NameOID.COMMON_NAME, "KRA Audit Signing Certificate"
                ),
            ]
        )

        # Build certificate (valid for 10 years like Dogtag)
        not_before = datetime.datetime.now(datetime.timezone.utc)
        not_after = not_before + datetime.timedelta(days=3650)

        # Use Dogtag-compatible audit signing key usage
        builder = (
            x509.CertificateBuilder()
            .subject_name(subject)
            .issuer_name(ca_cert.subject)
            .public_key(private_key.public_key())
            .serial_number(x509.random_serial_number())
            .not_valid_before(not_before)
            .not_valid_after(not_after)
            .add_extension(
                get_audit_key_usage_extension(),
                critical=True,
            )
            .add_extension(
                x509.BasicConstraints(ca=False, path_length=None),
                critical=True,
            )
        )

        # Sign with CA key using configured hash algorithm
        certificate = builder.sign(ca_key, hash_alg)

        # Import key and certificate to NSSDB
        logger.debug(
            f"Importing KRA audit key and certificate to NSSDB: "
            f"{kra_audit_nickname}"
        )
        nssdb.import_key_and_cert(
            kra_audit_nickname,
            private_key,
            certificate,
            trust_flags="u,u,Pu",  # Trusted peer for audit signing
        )

        # Save certificate to file (for compatibility/reference)
        # Note: Private key is NOT saved to disk - it stays in NSSDB only
        kra_audit_dir = Path(paths.IPATHINCA_DIR) / "kra"
        kra_audit_cert_path = kra_audit_dir / "kra_audit.crt"

        with open(kra_audit_cert_path, "wb") as f:
            f.write(
                certificate.public_bytes(encoding=serialization.Encoding.PEM)
            )
        kra_audit_cert_path.chmod(0o644)
        shutil.chown(kra_audit_cert_path, user="ipaca", group="ipaca")

        logger.debug(
            "KRA audit signing certificate generated in NSSDB successfully"
        )

    def _add_vault_container(self):
        """Create vault container structure in LDAP (same as Dogtag KRA)."""
        logger.debug("Creating vault container structure in LDAP")
        self._ldap_mod(
            "vault.ldif", {"SUFFIX": self.basedn}, raise_on_err=True
        )
        logger.debug("Vault container structure created successfully")

    def _register_kra_service(self):
        """Register KRA service in LDAP masters container."""
        logger.debug("Registering KRA service in LDAP")

        if not self.ldap.isconnected():
            self.ldap.connect()

        ldap = self.ldap

        # Create KRA service entry:
        # cn=KRA,cn={fqdn},cn=masters,cn=ipa,cn=etc,{basedn}
        service_dn = DN(
            ("cn", "KRA"),
            ("cn", self.fqdn),
            ("cn", "masters"),
            ("cn", "ipa"),
            ("cn", "etc"),
            self.basedn,
        )

        try:
            # Check if entry already exists
            ldap.get_entry(service_dn)
            logger.debug(f"KRA service entry already exists: {service_dn}")
        except errors.NotFound:
            logger.debug(f"Creating KRA service entry: {service_dn}")

            # Create the entry with proper object classes
            entry = ldap.make_entry(
                service_dn,
                objectClass=["nsContainer", "ipaConfigObject"],
                cn=["KRA"],
                ipaConfigString=["enabledService", "startOrder 51"],
            )
            ldap.add_entry(entry)
            logger.debug("KRA service entry created successfully")
