#! /usr/bin/python -E
# Authors: Rob Crittenden <rcritten@redhat.com>
#
# Copyright (C) 2007  Red Hat
# see file 'COPYING' for use and warranty information
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; version 2 only
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

from optparse import OptionParser
import ipa
import ipa.rpcclient
import ipa.ipaldap
import base64
import sys
import xmlrpclib

def usage():
    print "ipa-finduser <uid>"
    sys.exit()

def parse_options():
    parser = OptionParser()

    (options, args) = parser.parse_args()

    return options, args

def main():
    user={}
    (options, args) = parse_options()

    if len(args) != 1:
        usage()

    try:
        ent = ipa.rpcclient.get_user(args[0])
        entry = ipa.ipaldap.Entry(ent['dn'])
        for e in ent:
            entry.setValues(e, ent[e])
        print entry
    except xmlrpclib.Fault, fault:
        print fault.faultString

    return 0

main()