#! /usr/bin/python -E
# Authors: Rob Crittenden <rcritten@redhat.com>
#
# Copyright (C) 2007  Red Hat
# see file 'COPYING' for use and warranty information
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; version 2 only
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
import sys
try:
    from optparse import OptionParser
    import ipa
    import ipa.group
    import ipa.ipaclient as ipaclient
    import ipa.ipavalidate as ipavalidate
    import ipa.ipautil as ipautil
    import ipa.config
    import ipa.ipaerror
    import ipa.ipaadminutil as ipaadminutil

    import xmlrpclib
    import kerberos
    import ldap
    import errno
    import socket
except ImportError:
    print >> sys.stderr, """\
There was a problem importing one of the required Python modules. The
error was:

    %s
""" % sys.exc_value
    sys.exit(1)

def set_add_usage(which):
    print "%s option usage: --%s NAME=VALUE" % (which, which)

def parse_options():
    usage = "%prog [options] [group]"
    parser = OptionParser(usage=usage)
    parser.add_option("-d", "--description", dest="desc",
                      help="A description of this group")
    parser.add_option("-g", "--gid", dest="gid",
                      help="The gid to use for this group. If not included one is automatically set.")
    parser.add_option("-v", "--verbose", action="store_true", dest="verbose",
                      help="Verbose output of the XML-RPC connection")
    parser.add_option("--addattr", dest="addattr",
                      help="Adds an attribute or values to that attribute, attr=value",
                      action="append")
    parser.add_option("--setattr", dest="setattr",
                      help="Set an attribute, dropping any existing values that may exist",
                      action="append")

    ipa.config.add_standard_options(parser)
    options, args = parser.parse_args()

    if len(args) > 1:
        parser.error("too many arguments")

    ipa.config.init_config(options)

    return options, args

def main():
    cn = ""
    desc = ""

    group=ipa.group.Group()
    options, args = parse_options()

    if len(args) != 1:
        cn = ipautil.user_input_name("Group name")
    else:
        cn = args[0]
        try:
            ipaadminutil.check_name(cn)
        except ValueError, e:
            print "Group name " + str(e)
            return 1

    if not options.desc:
        desc = ipautil.user_input("Description", allow_empty = False)
    else:
        desc = options.desc
        if not ipavalidate.String(desc, notEmpty=True):
            print "Please enter a value"
            return 1

    if options.gid:
        group.setValue('gidnumber', options.gid)

    group.setValue('cn', cn)
    group.setValue('description', desc)

    if options.setattr:
        for s in options.setattr:
            s = s.split('=', 1)
            if len(s) != 2:
                set_add_usage("set")
                sys.exit(1)
            (attr,value) = s
            group.setValue(attr, value)

    if options.addattr:
        for a in options.addattr:
            a = a.split('=', 1)
            if len(a) != 2:
                set_add_usage("add")
                sys.exit(1)
            (attr,value) = a
            cvalue = group.getValue(attr)
            if cvalue:
                if isinstance(cvalue,str):
                    cvalue = [cvalue]
                value = cvalue + [value]
            group.setValue(attr, value)

    client = ipaclient.IPAClient(verbose=options.verbose)
    client.add_group(group)
    print cn + " successfully added"

    return 0

try:
    if __name__ == "__main__":
        sys.exit(main())
except SystemExit, e:
    sys.exit(e)
except KeyboardInterrupt, e:
    sys.exit(1)
except xmlrpclib.Fault, fault:
    if fault.faultCode == errno.ECONNREFUSED:
        print "The IPA XML-RPC service is not responding."
    else:
        print fault.faultString
    sys.exit(1)
except kerberos.GSSError, e:
    print "Could not initialize GSSAPI: %s/%s" % (ipautil.get_gsserror(e))
    sys.exit(1)
except xmlrpclib.ProtocolError, e:
    print "Unable to connect to IPA server: %s" % (e.errmsg)
    sys.exit(1)
except ipa.ipaerror.IPAError, e:
    print "%s" % (e.msg)
    sys.exit(1)
except socket.error, e:
    print e[1]
    print "Re-run with -v flag for more details."
except Exception, e:
    print "%s" % str(e)
    sys.exit(1)
