#! /usr/bin/python -E
# Authors: Rob Crittenden <rcritten@redhat.com>
#
# Copyright (C) 2007  Red Hat
# see file 'COPYING' for use and warranty information
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; version 2 only
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

import sys
from optparse import OptionParser
import ipa
import ipa.ipaclient as ipaclient
import ipa.config

import xmlrpclib
import kerberos

def usage():
    print "ipa-usermod [-c|--gecos STRING] [-d|--directory STRING] user"
    sys.exit(1)

def parse_options():
    parser = OptionParser()
    parser.add_option("-c", "--gecos", dest="gecos",
                      help="Set the GECOS field")
    parser.add_option("-d", "--directory", dest="directory",
                      help="Set the User's home directory")
    parser.add_option("-s", "--shell", dest="shell",
                      help="Set user's login shell to shell")
    parser.add_option("--usage", action="store_true",
                      help="Program usage")

    args = ipa.config.init_config(sys.argv)
    options, args = parser.parse_args(args)

    return options, args

def main():
    olduser={}
    newuser={}
    options, args = parse_options()

    if len(args) != 2:
        usage()

    client = ipaclient.IPAClient()
    u = client.get_user(args[1])
    olduser = u.toDict()
    newuser = u.toDict()

    if options.gecos:
        newuser['gecos'] = options.gecos
    if options.directory:
        newuser['homedirectory'] = options.directory
    if options.shell:
        newuser['loginshell'] = options.shell

    try:
        client.update_user(olduser, newuser)
        print args[1] + " successfully modified"
    except xmlrpclib.Fault, f:
        print f.faultString
        return 1
    except kerberos.GSSError, e:
        print "Could not initialize GSSAPI: %s/%s" % (e[0][0][0], e[0][1][0])
        return 1

    return 0

main()
