#! /usr/bin/python -E
# Authors: Rob Crittenden <rcritten@redhat.com>
#
# Copyright (C) 2007  Red Hat
# see file 'COPYING' for use and warranty information
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; version 2 only
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

import sys
from optparse import OptionParser
import ipa
import ipa.group
import ipa.ipaclient as ipaclient
import ipa.config
import ipa.ipaerror

import xmlrpclib
import kerberos
import ldap

def usage():
    print "ipa-groupmod [-a] [-r] user group"
    print "ipa-groupmod [-d|--desc description STRING] group"
    sys.exit(1)

def parse_options():
    parser = OptionParser()
    parser.add_option("-a", "--add", dest="add", action="store_true",
                      help="Add a user to the group")
    parser.add_option("-r", "--remove", dest="remove", action="store_true",
                      help="Remove a user from the group")
    parser.add_option("-d", "--description", dest="desc", 
                      help="Modify the description of the group")
    parser.add_option("--usage", action="store_true",
                      help="Program usage")

    args = ipa.config.init_config(sys.argv)
    options, args = parser.parse_args(args)

    if (not options.add and not options.remove) and (not options.desc):
        usage()

    return options, args

def get_group(client, group_cn):
    try:
        group = client.get_entry_by_cn(group_cn)
    except ipa.ipaerror.IPAError, e:
        print "%s" % e.message
        return None

    return group

def main():
    group=ipa.group.Group()
    options, args = parse_options()

    if (options.add or options.remove) and (len(args) != 3):
        usage()
    if (options.desc and (len(args) != 2)):
        usage()

    try:
        client = ipaclient.IPAClient()
        if options.add:
            group = get_group(client, args[2])
            if group is None:
                return 1
            client.add_user_to_group(args[1], group.dn)
            print args[1] + " successfully added to " + args[2]
        elif options.remove:
            group = get_group(client, args[2])
            if group is None:
                return 1
            client.remove_user_from_group(args[1], group.dn)
            print args[1] + " successfully removed"
        elif options.desc:
            group = get_group(client, args[1])
            if group is None:
                return 1
            group.setValue('description', options.desc)
            client.update_group(group)
            print args[1] + " successfully updated"
    except xmlrpclib.Fault, f:
        print f.faultString
        return 1
    except kerberos.GSSError, e:
        print "Could not initialize GSSAPI: %s/%s" % (e[0][0][0], e[0][1][0])
        return 1
    except xmlrpclib.ProtocolError, e:
        print "Unable to connect to IPA server: %s" % (e.errmsg)
        return 1
    except ipa.ipaerror.IPAError, e:
        print "%s" % (e.message)
        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main())
