topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 5750
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 6700
  master_2repl: &master_2repl
    name: master_2repl
    cpu: 4
    memory: 6700

jobs:
  fedora-27/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-f27
          name: freeipa/ci-master-f27
          version: 1.0.2
        timeout: 1800
        topology: *build

  fedora-27/installation:
    requires: [fedora-27/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-27/build_url}'
        test_suite: test_integration/test_installation.py
        template: *ci-master-f27
        timeout: 7200
        topology: *master_1repl

  fedora-27/forced_client_enrolment:
     requires: [fedora-27/build]
     priority: 50
     job:
       class: RunPytest
       args:
         build_url: '{fedora-27/build_url}'
         test_suite: test_integration/test_forced_client_reenrollment.py
         template: *ci-master-f27
         timeout: 3600
         topology: *master_1repl_1client
  
  fedora-27/backup_and_restore:
     requires: [fedora-27/build]
     priority: 50
     job:
       class: RunPytest
       args:
         build_url: '{fedora-27/build_url}'
         test_suite: test_integration/test_backup_and_restore.py
         template: *ci-master-f27
         timeout: 7200
         topology: *master_1repl_1client
  
  fedora-27/test_sudo:
     requires: [fedora-27/build]
     priority: 50
     job:
       class: RunPytest
       args:
         build_url: '{fedora-27/build_url}'
         test_suite: test_integration/test_sudo.py
         template: *ci-master-f27
         timeout: 3600
         topology: *master_1repl_1client
  
  fedora-27/test_http_kdc_proxy:
     requires: [fedora-27/build]
     priority: 50
     job:
       class: RunPytest
       args:
         build_url: '{fedora-27/build_url}'
         test_suite: test_integration/test_http_kdc_proxy.py
         template: *ci-master-f27
         timeout: 3600
         topology: *master_1repl_1client
  
  fedora-27/test_advise:
     requires: [fedora-27/build]
     priority: 50
     job:
       class: RunPytest
       args:
         build_url: '{fedora-27/build_url}'
         test_suite: test_integration/test_advise.py
         template: *ci-master-f27
         timeout: 3600
         topology: *master_1repl

  fedora-27/test_forced_client_reenrollment:
     requires: [fedora-27/build]
     priority: 50
     job:
       class: RunPytest
       args:
         build_url: '{fedora-27/build_url}'
         test_suite: test_integration/test_forced_client_reenrollment.py
         template: *ci-master-f27
         timeout: 3600
         topology: *master_1repl_1client

  fedora-27/test_testconfig:
     requires: [fedora-27/build]
     priority: 50
     job:
       class: RunPytest
       args:
         build_url: '{fedora-27/build_url}'
         test_suite: test_integration/test_testconfig.py
         template: *ci-master-f27
         timeout: 3600
         topology: *master_1repl

  fedora-27/test_customized_ds_config_install:
     requires: [fedora-27/build]
     priority: 50
     job:
       class: RunPytest
       args:
         build_url: '{fedora-27/build_url}'
         test_suite: test_integration/test_customized_ds_config_install.py
         template: *ci-master-f27
         timeout: 3600
         topology: *master_1repl

  fedora-27/test_kerberos_flags:
     requires: [fedora-27/build]
     priority: 50
     job:
       class: RunPytest
       args:
         build_url: '{fedora-27/build_url}'
         test_suite: test_integration/test_kerberos_flags.py
         template: *ci-master-f27
         timeout: 3600
         topology: *master_1repl_1client

  fedora-27/test_topologies:
     requires: [fedora-27/build]
     priority: 50
     job:
       class: RunPytest
       args:
         build_url: '{fedora-27/build_url}'
         test_suite: test_integration/test_topologies.py
         template: *ci-master-f27
         timeout: 3600
         topology: *master_1repl

  fedora-27/test_http_kdc_proxy:
     requires: [fedora-27/build]
     priority: 50
     job:
       class: RunPytest
       args:
         build_url: '{fedora-27/build_url}'
         test_suite: test_integration/test_http_kdc_proxy.py
         template: *ci-master-f27
         timeout: 3600
         topology: *master_1repl_1client
