#!/usr/bin/python

# Authors:
#   Jason Gerard DeRose <jderose@redhat.com>
#
# Copyright (C) 2008  Red Hat
# see file 'COPYING' for use and warranty information
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; version 2 only
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

"""
Command Line Interface to IPA.
"""

import sys
from ipalib.startup import api

def print_commands():
	print 'Commands:'
	m = api.max_cmd_len
	for c in api.commands:
		c = c.replace('_', '-')
		print '  %s  The help on %s' % (c.ljust(m), c)

def print_help(cmd):
	print 'Help on %s' % cmd

if len(sys.argv) < 2:
	print_commands()
	print 'Usage: ipa COMMAND [OPTIONS]'
	sys.exit(2)

cmd = sys.argv[1]

if cmd not in api.commands:
	print_commands()
	print 'ipa: ERROR: unknown command %r' % cmd
	sys.exit(2)
