#!/usr/bin/python

# Authors:
#   Jason Gerard DeRose <jderose@redhat.com>
#
# Copyright (C) 2008  Red Hat
# see file 'COPYING' for use and warranty information
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; version 2 only
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

"""
Command Line Interface to IPA.

Just proof of concept stuff in here right now.
"""

import sys
from ipalib.startup import api

def _(msg):
	"""
	Dummy gettext function for testing.
	"""
	return msg


def print_commands():
	print 'Commands:'
	m = api.max_cmd_len
	for cmd in api.cmd:
		print '  %s  %s' % (str(cmd).ljust(m), cmd.get_doc(_))

def print_help(cmd):
	print 'Help on %s' % cmd

def print_api():
	def print_ns(name):
		ns = getattr(api, name)
		print '%d %s:' % (len(ns), name)
		m = max(len(i.name) for i in ns)
		for i in ns:
			print ' %s %r' % (i.name.ljust(m), i)

	for n in ['cmd', 'obj', 'prop']:
		print_ns(n)
		print ''


if len(sys.argv) < 2:
	print_commands()
	print 'Usage: ipa COMMAND [OPTIONS]'
	sys.exit(2)
name= sys.argv[1]
if name == '_api_':
	print_api()
	sys.exit()
elif name not in api.cmd:
	print_commands()
	print 'ipa: ERROR: unknown command %r' % name
	sys.exit(2)
api.cmd[name]()
