specfile_path: freeipa.spec
actions:
  post-upstream-clone:
    - make -f .copr/Makefile srpm outdir=.

# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: freeipa
# downstream (Fedora) RPM package name
downstream_package_name: freeipa
upstream_project_url: https://github.com/abbra/freeipa

srpm_build_deps:
  - make
  - dnf
  - dnf5-plugins

jobs:
- job: copr_build
  trigger: commit
  branch: sysaccounts
  owner: abbra
  project: sysaccounts

