#!/usr/bin/python2 -E
#
# Authors:
#   Rob Crittenden <rcritten@redhat.com>
#
# Copyright (C) 2012  Red Hat
# see file 'COPYING' for use and warranty information
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import syslog
import traceback
from ipapython import dogtag
from ipalib import api
from ipaplatform import services
from ipaserver.install import certs


def main():
    api.bootstrap(context='restart')
    api.finalize()

    configured_constants = dogtag.configured_constants(api)
    dogtag_service = services.knownservices[configured_constants.SERVICE_NAME]
    dogtag_instance = configured_constants.PKI_INSTANCE_NAME

    certs.renewal_lock.acquire('renew_ca_cert')

    syslog.syslog(syslog.LOG_NOTICE, "Stopping %s" % dogtag_service.service_name)
    try:
        dogtag_service.stop(dogtag_instance)
    except Exception, e:
        syslog.syslog(
            syslog.LOG_ERR, "Cannot stop %s: %s" % (dogtag_service.service_name, e))
    else:
        syslog.syslog(
            syslog.LOG_NOTICE, "Stopped %s" % dogtag_service.service_name)

try:
    main()
except Exception:
    syslog.syslog(syslog.LOG_ERR, traceback.format_exc())
