.\" A man page for ipa-delservice
.\" Copyright (C) 2007 Red Hat, Inc.
.\" 
.\" This is free software; you can redistribute it and/or modify it under
.\" the terms of the GNU Library General Public License as published by
.\" the Free Software Foundation; version 2 only
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Library General Public
.\" License along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\" 
.\" Author: Rob Crittenden <rcritten@redhat.com>
.\" 
.TH "ipa-delservice" "1" "Jan 11 2008" "freeipa" ""
.SH "NAME"
ipa\-delservice \- Delete a service principal

.SH "SYNOPSIS"
ipa\-delservice \fIprincipal\fR

.SH "DESCRIPTION"
Deletes a service principal with name \fIprincipal\fR.

.SH "EXIT STATUS"
0 on success

1 if an error occurred

2 if not exactly one matching entries was found
