.\" A man page for ipa-deldelegation
.\" Copyright (C) 2007 Red Hat, Inc.
.\" 
.\" This is free software; you can redistribute it and/or modify it under
.\" the terms of the GNU Library General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Library General Public
.\" License along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\" 
.\" Author: Rob Crittenden <rcritten@redhat.com>
.\" 
.TH "ipa-deldelegation" "1" "Oct 24 2007" "freeipa" ""
.SH "NAME"
ipa\-deldelegation \- Remove a delegation

.SH "SYNOPSIS"
ipa\-deldelegation \fIname\fR

.SH "DESCRIPTION"
Removes an existing delegation named \fIname\fR.

A delegation is used to grant write access to certain attributes from one group to another. ipa\-deldelegation removes this access.
.SH "EXIT STATUS"
0 if the delegation was removed successfully

1 if an error occurred

2 if no matching delegation was found
