.\" A man page for ipa-findgroup
.\" Copyright (C) 2007 Red Hat, Inc.
.\" 
.\" This is free software; you can redistribute it and/or modify it under
.\" the terms of the GNU Library General Public License as published by
.\" the Free Software Foundation; version 2 only
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Library General Public
.\" License along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\" 
.\" Author: Rob Crittenden <rcritten@redhat.com>
.\" 
.TH "ipa-findgroup" "1" "Oct 10 2007" "freeipa" ""
.SH "NAME"
ipa\-findgroup \- Find a group

.SH "SYNOPSIS"
ipa\-findgroup \fIstring\fR

.SH "OPTIONS"
.TP 
\fB\-v\fR, \fB\-\-verbose\fR
Display the XML\-RPC request and response for more verbose debugging output.
.SH "DESCRIPTION"
Searches for a group that contains \fIstring\fR.

The search is a substring search in the name and description attributes.

All entries that match are displayed.
.SH "EXIT STATUS"
0 if one or more entries were found

1 if an error occurred

2 if no matching entries were found
