.\" A man page for ipa-moduser
.\" Copyright (C) 2007 Red Hat, Inc.
.\" 
.\" This is free software; you can redistribute it and/or modify it under
.\" the terms of the GNU Library General Public License as published by
.\" the Free Software Foundation; version 2 only
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Library General Public
.\" License along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\" 
.\" Author: Rob Crittenden <rcritten@redhat.com>
.\" 
.TH "ipa-moduser" "1" "Oct 10 2007" "freeipa" ""
.SH "NAME"
ipa\-moduser \- Modify a user
.SH "SYNOPSIS"
ipa\-moduser [\fIOPTION\fR]... \fIname\fR

.SH "DESCRIPTION"
Updates the user \fIname\fR.
.SH "OPTIONS"
.TP 
\fB\-a\fR, \fB\-\-activate\fR
Activate a user that was previously inactivated
.TP 
\fB\-c\fR, \fB\-\-gecos\fR=\fIGECOS\fR
Set the gecos field of the user. This is traditionally the user's full name.
.TP 
\fB\-d\fR, \fB\-\-directory\fR=\fIdirectory\fR
Set user's home directory
.TP 
\fB\-f\fR, \fB\-\-firstname\fR=\fINAME\fR
Set user's first name
.TP 
\fB\-l\fR, \fB\-\-lastname\fR=\fINAME\fR
Set user's last name
.TP 
\fB\-s\fR, \fB\-\-shell\fR=\fIshell\fR
Set user's login shell
.TP 
\fB\-\-addattr\fR \fIattr=value\fR
Add a new attribute, or value to an existing attribute
.TP 
\fB\-\-delattr\fR \fIattr=value\fR
Remove an attribute and all values
.TP 
\fB\-\-setattr\fR \fIattr=value\fR
Set an attribute to a new value, removing all old ones
.SH "EXIT STATUS"
The exit status is 0 on success, nonzero on error.
