.\" A man page for ipa-passwd
.\" Copyright (C) 2007 Red Hat, Inc.
.\" 
.\" This is free software; you can redistribute it and/or modify it under
.\" the terms of the GNU Library General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Library General Public
.\" License along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\" 
.\" Author: Rob Crittenden <rcritten@redhat.com>
.\" 
.TH "ipa-passwd" "1" "Oct 10 2007" "freeipa" ""
.SH "NAME"
ipa\-passwd \- Change a user's password
.SH "SYNOPSIS"
ipa\-password [\fIuser\fR]

.SH "DESCRIPTION"
Changes the current user's password. If a \fIuser\fR is included on the command\-line then that user's password is modified.

The user is the name in the kerberos principal, so it may not match username.
.SH "EXIT STATUS"
The exit status is 0 on success, nonzero on error.
