.\" A man page for ipa-findservice
.\" Copyright (C) 2007 Red Hat, Inc.
.\" 
.\" This is free software; you can redistribute it and/or modify it under
.\" the terms of the GNU Library General Public License as published by
.\" the Free Software Foundation; version 2 only
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Library General Public
.\" License along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\" 
.\" Author: Rob Crittenden <rcritten@redhat.com>
.\" 
.TH "ipa-findservice" "1" "Jan 11 2008" "freeipa" ""
.SH "NAME"
ipa\-findservice \- Find a service principal
.SH "SYNOPSIS"
ipa\-findservice \fIstring\fR

.SH "DESCRIPTION"
Searches for a service principal that contains \fIstring\fR.

The search is a substring search in the service principal. You can search for all principals for a given host, by service or a substring.

All entries that match are displayed.
.SH "EXAMPLES"
Find all ldap service principals issued by the IPA KDC:

    # ipa\-findservice ldap

Find all service principals for ipa.example.com:

    # ipa\-findservice ipa.example.com
.SH "EXIT STATUS"
0 if one or more entries were found

1 if an error occurred

2 if no matching entries were found
