.\" A man page for ipa-moddelegation
.\" Copyright (C) 2007 Red Hat, Inc.
.\" 
.\" This is free software; you can redistribute it and/or modify it under
.\" the terms of the GNU Library General Public License as published by
.\" the Free Software Foundation; version 2 only
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Library General Public
.\" License along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\" 
.\" Author: Rob Crittenden <rcritten@redhat.com>
.\" 
.TH "ipa-moddelegation" "1" "Oct 24 2007" "freeipa" ""
.SH "NAME"
ipa\-moddelegation \- Modify an existing delegation

.SH "SYNOPSIS"
ipa\-moddelegation [\fIOPTION\fR]... \fIname\fR

.SH "DESCRIPTION"
Modifies an existing delegation named \fIname\fR.

A delegation is used to grant access to certain attributes from one group to another.
.SH "OPTIONS"
.TP 
\fB\-a\fR, \fB\-\-attributes\fR=\fIATTRIBUTES\fR
A comma\-separated list of the the \f[SM]attributes\fR that may be written by the source group. This list of attributes replaces the list in the existing delegation.

.TP 
\fB\-s\fR, \fB\-\-source\fR=\fISOURCE\fR
The name of the group that is being granted write permission.

.TP 
\fB\-t\fR, \fB\-\-target\fR=\fITARGET\fR
The name of the group that will be written to.

.PP 
At least one of \-a, \-s or \-t is required.
.SH "EXIT STATUS"
0 if the delegation was updated successfully

1 if an error occurred

2 if no matching delegation was found
