#!/usr/bin/python3
#
# Copyright (C) 2015  FreeIPA Contributors see COPYING for license
#

# Documentation can be found at:
#     http://freeipa.org/page/LdapUpdate
#     http://www.freeipa.org/page/V4/Server_Upgrade_Refactoring

from ipaserver.install.ipa_server_upgrade import ServerUpgrade

ServerUpgrade.run_cli()
