#!/usr/bin/env python
# Authors: Rob Crittenden <rcritten@redhat.com>
# Authors: Simo Sorce <ssorce@redhat.com>
#
# Copyright (C) 2009  Red Hat
# see file 'COPYING' for use and warranty information
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import sys
try:
    from optparse import OptionParser
    from ipapython import ipautil, config
    from ipaserver.install import installutils
    from ipaserver.install.ldapupdate import LDAPUpdate, BadSyntax
    from ipaserver.plugins.ldap2 import ldap2
    from ipalib import api, errors
    import logging
except ImportError:
    print >> sys.stderr, """\
There was a problem importing one of the required Python modules. The
error was:

    %s
""" % sys.exc_value
    sys.exit(1)

nis_config_dn = "cn=NIS Server,cn=plugins,cn=config"
compat_dn = "cn=Schema Compatibility,cn=plugins,cn=config"

def parse_options():
    usage = "%prog [options] <enable|disable>\n"
    usage += "%prog [options]\n"
    parser = OptionParser(usage=usage, formatter=config.IPAFormatter())

    parser.add_option("-d", "--debug", action="store_true", dest="debug",
                      help="Display debugging information about the update(s)")
    parser.add_option("-y", dest="password",
                      help="File containing the Directory Manager password")

    config.add_standard_options(parser)
    options, args = parser.parse_args()

    config.init_config(options)

    return options, args

def get_dirman_password():
    """Prompt the user for the Directory Manager password and verify its
       correctness.
    """
    password = installutils.read_password("Directory Manager", confirm=False, validate=False)

    return password

def get_entry(dn, conn):
    """
    Return the entry for the given DN. If the entry is not found return
    None.
    """
    entry = None
    try:
        (dn, entry) = conn.get_entry(dn, normalize=False)
    except errors.NotFound:
        pass
    return entry

def main():
    retval = 0
    loglevel = logging.ERROR
    files = ['/usr/share/ipa/nis.uldif']
    servicemsg = ""

    options, args = parse_options()
    if options.debug:
        loglevel = logging.DEBUG

    if len(args) != 1:
        sys.exit("You must specify one action, either enable or disable")
    elif args[0] != "enable" and args[0] != "disable":
        sys.exit("Unrecognized action [" + args[0] + "]")

    logging.basicConfig(level=loglevel,
                        format='%(levelname)s %(message)s')

    dirman_password = ""
    if options.password:
        pw = ipautil.template_file(options.password, [])
        dirman_password = pw.strip()
    else:
        dirman_password = get_dirman_password()

    api.bootstrap(context='cli', debug=options.debug)
    api.finalize()

    conn = None
    try:
        ldapuri = 'ldap://%s' % installutils.get_fqdn()
        try:
            conn = ldap2(shared_instance=False, ldap_uri=ldapuri, base_dn='')
            conn.connect(
                bind_dn='cn=directory manager', bind_pw=dirman_password
            )
        except errors.ACIError:
            sys.exit("Incorrect password")
        except errors.LDAPError, lde:
            sys.exit("An error occurred while connecting to the server: %s" % str(lde))

        if args[0] == "enable":
            compat = get_entry(compat_dn, conn)
            if compat is None:
                sys.exit("The compat plugin needs to be enabled: ipa-compat-manage enable")
            entry = None
            try:
                entry = get_entry(nis_config_dn, conn)
            except errors.LDAPError, lde:
                print "An error occurred while talking to the server."
                print lde
                retval = 1

            # Enable either the portmap or rpcbind service
            try:
                ipautil.run(["/sbin/chkconfig", "portmap", "on"])
                servicemsg = "portmap"
            except ipautil.CalledProcessError, cpe:
                if cpe.returncode == 1:
                    try:
                        ipautil.run(["/sbin/chkconfig", "rpcbind", "on"])
                        servicemsg = "rpcbind"
                    except ipautil.CalledProcessError, cpe:
                        print "Unable to enable either portmap or rpcbind"
                        retval = 3

            # The cn=config entry for the plugin may already exist but it
            # could be turned off, handle both cases.
            if (entry is None or
              entry.get('nsslapd-pluginenabled', [''])[0].lower() == 'off'):
                # Already configured, just enable the plugin
                print "Enabling plugin"
                ld = LDAPUpdate(dm_password=dirman_password, sub_dict={})
                if ld.update(files) != True:
                    retval = 1
                mod = {'nsslapd-pluginenabled': 'on'}
                try:
                    conn.update_entry(nis_config_dn, mod, normalize=False)
                except errors.EmptyModlist:
                    # plugin is already enabled, silently continue
                    pass
            else:
                print "Plugin already Enabled"
                retval = 2

        elif args[0] == "disable":
            try:
                mod = {'nsslapd-pluginenabled': 'off'}
                conn.update_entry(nis_config_dn, mod, normalize=False)
            except errors.NotFound:
                print "Plugin is already disabled"
                retval = 2
            except errors.EmptyModlist:
                print "Plugin is already disabled"
                retval = 2
            except errors.LDAPError, lde:
                print "An error occurred while talking to the server."
                print lde
                retval = 1

            # delete the netgroups compat area.
            try:
                conn.delete_entry('cn=ng,cn=Schema Compatibility,cn=plugins,cn=config', normalize=False)
            except errors.NotFound:
                pass
            except errors.DatabaseError, dbe:
                print "An error occurred while talking to the server."
                print lde
                retval = 1
            except errors.LDAPError, lde:
                print "An error occurred while talking to the server."
                print lde
                retval = 1


        else:
            retval = 1

        if retval == 0:
            print "This setting will not take effect until you restart Directory Server."

            if args[0] == "enable":
                print "The %s service may need to be started." % servicemsg

    finally:
        if conn and conn.isconnected():
            conn.disconnect()

    return retval

try:
    if __name__ == "__main__":
        sys.exit(main())
except BadSyntax, e:
    print "There is a syntax error in this update file:"
    print "  %s" % e
    sys.exit(1)
except RuntimeError, e:
    print "%s" % e
    sys.exit(1)
except SystemExit, e:
    sys.exit(e)
except KeyboardInterrupt, e:
    sys.exit(1)
except config.IPAConfigError, e:
    print "An IPA server to update cannot be found. Has one been configured yet?"
    print "The error was: %s" % e
    sys.exit(1)
except errors.LDAPError, e:
    print "An error occurred while performing operations: %s" % e
    sys.exit(1)
