#! /usr/bin/python2 -E
# Authors: Karl MacMillan <kmacmillan@mentalrootkit.com>
#
# Copyright (C) 2007  Red Hat
# see file 'COPYING' for use and warranty information
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from ipapython.install import cli
from ipaplatform.paths import paths
from ipaserver.install.server import Replica


ReplicaInstall = cli.install_tool(
    Replica,
    command_name='ipa-replica-install',
    positional_arguments='replica_file',
    usage='%prog [options] REPLICA_FILE',
    log_file_name=paths.IPAREPLICA_INSTALL_LOG,
    debug_option=True,
)


ReplicaInstall.run_cli()
