#
# Template for temporary test commit
#
# $ ln -sf ipatests/prci_definitions/temp_commit.yaml .freeipa-pr-ci.yaml
#

topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 6450
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 7400

jobs:
  fedora-28/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-f28
          name: freeipa/ci-master-f28
          version: 0.1.9
        timeout: 1800
        topology: *build

  fedora-28/temp_commit:
    requires: [fedora-28/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{fedora-28/build_url}'
        test_suite: test_integration/test_REPLACEME.py
        template: *ci-master-f28
        timeout: 3600
        topology: *master_1repl_1client
