# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
# insert parent directory with ipalib and ipasphinx
sys.path.insert(0, os.path.abspath('..'))


# -- Project information -----------------------------------------------------

project = 'FreeIPA'
copyright = '2020, FreeIPA Contributors'
author = 'FreeIPA Contributors'

# The short X.Y version
version = '4.9-dev'

# The full version, including alpha/beta/rc tags
release = '4.9-dev'

master_doc = 'index'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'ipasphinx.ipabase',
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.viewcode',
    'm2r',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    '_build', 'Thumbs.db', '.DS_Store', 'workshop/README.rst', '.venv/*'
]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'default'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']

# -- Options for sources -----------------------------------------------------

source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
# intersphinx_mapping = {'https://docs.python.org/': None}

# -- Options for man page builder --------------------------------------------

man_pages = [
    ("man/default.conf.5", "default.conf", "IPA configuration file", None,
     5),
    ("man/ipa-adtrust-install.1", "ipa-adtrust-install",
     "Prepare an IPA server to be able to establish", None, 1),
    ("man/ipa-advise.1", "ipa-advise",
     "Provide configurations advice for various use cases.", None, 1),
    ("man/ipa-backup.1", "ipa-backup", "Back up an IPA master", None, 1),
    ("man/ipa-ca-install.1", "ipa-ca-install", "Install a CA on a server",
     None, 1),
    ("man/ipa-cacert-manage.1", "ipa-cacert-manage",
     "Manage CA certificates in IPA", None, 1),
    ("man/ipa-cert-fix.1", "ipa-cert-fix", "Renew expired certificates",
     None, 1),
    ("man/ipa-certupdate.1", "ipa-certupdate",
     "Update local IPA certificate databases with", None, 1),
    ("man/ipa-client-automount.1", "ipa-client-automount",
     "Configure automount and NFS for IPA", None, 1),
    ("man/ipa-client-install.1", "ipa-client-install",
     "Configure an IPA client", None, 1),
    ("man/ipa-client-samba.1", "ipa-client-samba",
     "Configure Samba file server on an IPA client", None, 1),
    ("man/ipa-compat-manage.1", "ipa-compat-manage",
     "Enables or disables the schema compatibility plugin", None, 1),
    ("man/ipa-crlgen-manage.1", "ipa-crlgen-manage",
     "Enables or disables CRL generation", None, 1),
    ("man/ipa-csreplica-manage.1", "ipa-csreplica-manage",
     "Manage an IPA CS replica", None, 1),
    ("man/ipa-dns-install.1", "ipa-dns-install",
     "Add DNS as a service to an IPA server", None, 1),
    ("man/ipa-getkeytab.1", "ipa-getkeytab",
     "Get a keytab for a Kerberos principal", None, 1),
    ("man/ipa-join.1", "ipa-join",
     "Join a machine to an IPA realm and get a keytab for the host "
     "service principal", None, 1),
    ("man/ipa-kra-install.1", "ipa-kra-install",
     "Install a KRA on a server", None, 1),
    ("man/ipa-ldap-updater.1", "ipa-ldap-updater",
     "Update the IPA LDAP configuration", None, 1),
    ("man/ipa-managed-entries.1", "ipa-managed-entries",
     "Enables or disables the schema Managed Entry", None, 1),
    ("man/ipa-nis-manage.1", "ipa-nis-manage",
     "Enables or disables the NIS listener plugin", None, 1),
    ("man/ipa-otptoken-import.1", "ipa-otptoken-import",
     "Imports OTP tokens from RFC 6030 XML file", None, 1),
    ("man/ipa-pkinit-manage.1", "ipa-pkinit-manage",
     "Enables or disables PKINIT", None, 1),
    ("man/ipa-replica-conncheck.1", "ipa-replica-conncheck",
     "Check a replica-master network connection before", None, 1),
    ("man/ipa-replica-install.1", "ipa-replica-install",
     "Create an IPA replica", None, 1),
    ("man/ipa-replica-manage.1", "ipa-replica-manage",
     "Manage an IPA replica", None, 1),
    ("man/ipa-restore.1", "ipa-restore", "Restore an IPA master", None, 1),
    ("man/ipa-rmkeytab.1", "ipa-rmkeytab",
     "Remove a kerberos principal from a keytab", None, 1),
    ("man/ipa-server-certinstall.1", "ipa-server-certinstall",
     "Install new SSL server certificates", None, 1),
    ("man/ipa-server-install.1", "ipa-server-install",
     "Configure an IPA server", None, 1),
    ("man/ipa-server-upgrade.1", "ipa-server-upgrade",
     "upgrade IPA server", None, 1),
    ("man/ipa-winsync-migrate.1", "ipa-winsync-migrate",
     "Seamless migration of AD users created by winsync", None, 1),
    ("man/ipa.1", "ipa", "IPA command-line interface", None, 1),
    ("man/ipactl.8", "ipactl", "IPA Server Control Interface", None, 8),
]
