#!/usr/bin/python

import xmlrpclib
    
server = xmlrpclib.ServerProxy("http://localhost:8888/")
    
print server.system.listMethods()
print server.system.methodHelp("user_add")

try:
    args="admin"
    kw = {'givenname':'Joe', 'sn':'Smith'}
    result = server.user_add(args, kw)
    print "returned %s" % result
except xmlrpclib.Fault, e:
    print e.faultString

try:
    args="admin"
    result = server.user_find(args)
    print "returned %s" % result
except xmlrpclib.Fault, e:
    print e.faultString
