version: '2.1'
services:
  master:
    image: ${IPA_DOCKER_IMAGE}
    build: .
    cap_add:
    - SYS_ADMIN
    - DAC_READ_SEARCH
    - NET_ADMIN
    - NET_BROADCAST
    - NET_RAW
    security_opt:
    - apparmor:unconfined
    - seccomp:./seccomp.json
    mem_limit: "${IPA_TESTS_SERVER_MEM_LIMIT}"
    memswap_limit: "${IPA_TESTS_SERVER_MEMSWAP_LIMIT}"
    volumes:
    - /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd
    - ${PROJECT_DIR}/ipa-test-config.yaml:/root/.ipa/ipa-test-config.yaml:ro
    - ${BUILD_REPOSITORY_LOCALPATH}:${IPA_TESTS_REPO_PATH}
    networks:
      ipanet:
        ipv4_address: 192.168.159.2

  replica:
    image: ${IPA_DOCKER_IMAGE}
    build: .
    cap_add:
    - SYS_ADMIN
    - DAC_READ_SEARCH
    - NET_ADMIN
    - NET_BROADCAST
    - NET_RAW
    security_opt:
    - apparmor:unconfined
    - seccomp:./seccomp.json
    mem_limit: "${IPA_TESTS_REPLICA_MEM_LIMIT}"
    memswap_limit: "${IPA_TESTS_REPLICA_MEMSWAP_LIMIT}"
    volumes:
    - /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd
    - ${BUILD_REPOSITORY_LOCALPATH}:${IPA_TESTS_REPO_PATH}:ro
    networks:
      ipanet:
        ipv4_address: 192.168.159.3

  client:
    image: ${IPA_DOCKER_IMAGE}
    build: .
    cap_add:
    - SYS_ADMIN
    - DAC_READ_SEARCH
    - NET_ADMIN
    - NET_BROADCAST
    - NET_RAW
    security_opt:
    - apparmor:unconfined
    - seccomp:./seccomp.json
    mem_limit: "${IPA_TESTS_CLIENT_MEM_LIMIT}"
    memswap_limit: "${IPA_TESTS_CLIENT_MEMSWAP_LIMIT}"
    volumes:
    - /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd
    - ${BUILD_REPOSITORY_LOCALPATH}:${IPA_TESTS_REPO_PATH}:ro
    # nfs server
    - ./exports:/exports
    - /lib/modules:/lib/modules:ro
    networks:
      ipanet:
        ipv4_address: 192.168.159.4

networks:
  ipanet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.159.0/24
    internal: false
