/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "KeytabModule"
 * 	found in "ipa.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types -S /home/abokovoy/src/upstream/asn1c/skeletons`
 */

#include "KrbKey.h"

asn_TYPE_member_t asn_MBR_KrbKey_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct KrbKey, key),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TypeValuePair,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"key"
		},
	{ ATF_POINTER, 2, offsetof(struct KrbKey, salt),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TypeValuePair,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"salt"
		},
	{ ATF_POINTER, 1, offsetof(struct KrbKey, s2kparams),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"s2kparams"
		},
};
static const int asn_MAP_KrbKey_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_KrbKey_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_KrbKey_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* key */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* salt */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* s2kparams */
};
asn_SEQUENCE_specifics_t asn_SPC_KrbKey_specs_1 = {
	sizeof(struct KrbKey),
	offsetof(struct KrbKey, _asn_ctx),
	asn_MAP_KrbKey_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_KrbKey_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_KrbKey = {
	"KrbKey",
	"KrbKey",
	&asn_OP_SEQUENCE,
	asn_DEF_KrbKey_tags_1,
	sizeof(asn_DEF_KrbKey_tags_1)
		/sizeof(asn_DEF_KrbKey_tags_1[0]), /* 1 */
	asn_DEF_KrbKey_tags_1,	/* Same as above */
	sizeof(asn_DEF_KrbKey_tags_1)
		/sizeof(asn_DEF_KrbKey_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_KrbKey_1,
	3,	/* Elements count */
	&asn_SPC_KrbKey_specs_1	/* Additional specs */
};

