# set to 1 to produce a debug build of all subprojects
#export DEBUG=1

# set to 1 to build for 64bit
#export BUILD64=0

ifeq ($(DEBUG),1)
	export CFLAGS = -g -Wall -Wshadow
	export LDFLAGS = -g
else
	export CFLAGS = -O2 -Wall -Wshadow
endif

DIRSRV=dirsrv
PREFIX?=$(DESTDIR)/usr
LIBDIR?=$(DESTDIR)/usr/lib
SHAREDIR?=$(PREFIX)/share/ipa
PLUGINDIR?=$(LIBDIR)/$(DIRSRV)/plugins
SBINDIR?=$(PREFIX)/sbin
INITDIR?=$(DESTDIR)/etc/rc.d/init.d
PYTHONDIR?=$(SHAREDIR)/ipaserver